### ISSUE TITLE
Application::getRequest() must not be called statically

### ISSUE THREAD

**Issue by ctgraham** [publons/ojs_3_plugin#18]
`Application::getRequest()` must not be called statically.  This will trigger a fatal error in PHP8.
E.g.:
```
PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in plugins/generic/publons/PublonsPlugin.inc.php:166
Stack trace:
#0 lib/pkp/classes/plugins/HookRegistry.inc.php(107): PublonsPlugin->handleRequest()
#1 lib/pkp/classes/core/PKPPageRouter.inc.php(202): HookRegistry::call()
#2 lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
#3 lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()
#4 index.php(68): PKPApplication->execute()
#5 {main}
  thrown in plugins/generic/publons/PublonsPlugin.inc.php on line 166
```

**Comment by Alex-nz** [comment]
We have updated this plugin during last year:

* rebranded to Web of Science
* fixed some known issues
* covered all versions up to the most recent 3.4.0.9
* added to plugin gallery

We now have 2 new repositories for the rebranded and fixed version of this plugin:
OJS 3.1 - 3.3: https://github.com/clarivate/wos_reviewer_recognition_plugin_ojs_old
OJS 3.4 +: https://github.com/clarivate/wos_reviewer_recognition_plugin_ojs_3
